# Generated by Django 4.0.3 on 2022-07-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoldShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=10)),
                ('order_date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('entry_date', models.DateField()),
                ('buy_invoice_nr', models.CharField(blank=True, max_length=30)),
                ('buy_invoice_date', models.DateField(blank=True)),
                ('storage_nr', models.IntegerField()),
                ('exit_date', models.DateField()),
                ('sell_invoice_nr', models.CharField(blank=True, max_length=30)),
                ('sell_invoice_date', models.DateField(blank=True)),
                ('money_income_date', models.DateField(blank=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('tracking_nr', models.CharField(blank=True, max_length=30)),
                ('stockx_nr', models.CharField(blank=True, max_length=30)),
                ('cw', models.CharField(blank=True, max_length=20)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='InStorageShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=10)),
                ('order_date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('entry_date', models.DateField()),
                ('buy_invoice_nr', models.CharField(blank=True, max_length=30)),
                ('buy_invoice_date', models.DateField(blank=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.seller')),
            ],
        ),
        migrations.CreateModel(
            name='IncommingShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=10)),
                ('order_date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.seller')),
            ],
        ),
    ]
