# Generated by Django 4.0.3 on 2022-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_incommingshoe_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instorageshoe',
            name='buy_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instorageshoe',
            name='buy_invoice_nr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
