# Generated by Django 4.0.3 on 2022-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_instorageshoe_buy_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instorageshoe',
            name='buy_invoice_nr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='soldshoe',
            name='buy_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldshoe',
            name='money_income_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldshoe',
            name='sell_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
