# Generated by Django 4.0.3 on 2022-10-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_soldshoe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='incommingshoe',
            name='cw',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incommingshoe',
            name='order_nr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='instorageshoe',
            name='cw',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='instorageshoe',
            name='order_nr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='instorageshoe',
            name='storage_nr',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='soldshoe',
            name='order_nr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='incommingshoe',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instorageshoe',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='soldshoe',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='soldshoe',
            name='storage_nr',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
